// Report-only diff between wh11ed's hand-transcribed CORE RULES prose and wh40k-appdata's
// factions/_core-rules.json (generated by that repo's build-factions.mjs from the Core Rules
// publication). This is the one large data pillar that sync-appdata.mjs / sync-tracker.mjs
// never touched — the rulebook text in basicRules/battleRound/advancedRules/battlefields
// (sections 01-23). Sections 24 (Core Abilities → reference.js) and 25 (Muster → muster.js)
// have a different shape and are a follow-up; this pilot covers the four section-array files.
//
// Usage:
//   node scripts/sync-core.mjs [numPrefix]   # e.g. "03" for just the Moving section
//   node scripts/sync-core.mjs               # all of 01-23
//
// Matching is by rule NUMBER (wh11ed `sectionNum` == appdata container subtitle / numbered
// accordion title, e.g. "03.01.02") — a far more stable key than the rule title, which both
// sides paraphrase. For every number it reports presence/absence and, for matched numbers, a
// crude normalized word-overlap ratio so wording drift is visible and quantifiable. Prose is
// NOT expected to match verbatim: wh11ed enriches it with gloss tokens, cross-references and
// hand-fixed wording. The overlap ratio is a triage signal — low overlap = go read both — not
// a pass/fail gate. Report only; nothing is written.
import { ROOT, APPDATA, loadJson, loadModule } from './lib/sync-common.mjs'
import path from 'node:path'

// Section-array files (each `{ en: Section[] }` with subsections/children carrying sectionNum):
// basicRules 01-06, battleRound 07-12, battlefields 13-16, advancedRules 17-23, muster 25.
// Section 24 (Core Abilities) is reference.js's flat `coreAbilities` list, wired separately below.
const FILES = ['basicRules', 'battleRound', 'advancedRules', 'battlefields', 'muster']

// Strip wh11ed body markup down to comparable words: drop image blocks, unwrap gloss/def
// tokens to their visible label, drop block/inline markers, keep the prose.
function normText(s) {
  return (s || '')
    .replace(/\[img:[^\]]*\]/g, ' ')
    .replace(/\[(?:gloss|def):[^:\]]*:([^\]]*)\]/g, '$1') // [gloss:id:label] / [def:id:label] → label
    .replace(/\{[a-z]+:([^}]*)\}/gi, '$1') // {red:TEXT} → TEXT
    .replace(/<\/?[a-z]+>/gi, ' ') // appdata <b>/<k> tags
    .replace(/[*_#`]/g, ' ') // markdown emphasis / headings
    .replace(/[▪◈◆→]/g, ' ') // block markers
    .replace(/[’‘`]/g, "'")
    .toLowerCase()
    .replace(/[^a-z0-9' ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}
const words = (s) => new Set(normText(s).split(' ').filter(Boolean))
function overlap(a, b) {
  const wa = words(a)
  const wb = words(b)
  if (!wa.size && !wb.size) return 1
  if (!wa.size || !wb.size) return 0
  let inter = 0
  for (const w of wa) if (wb.has(w)) inter++
  return inter / (wa.size + wb.size - inter) // Jaccard
}

// Flatten a wh11ed section-array file's EN tree into num → { title, body, file }.
function flattenWh11ed(sections, file, out) {
  const walk = (node) => {
    const num = node.sectionNum || node.num
    // Section-level nodes keep their intro prose in `description`; subsections use `body`.
    if (num) out.set(num, { title: node.title || '', body: node.body || node.description || '', file })
    for (const c of node.subsections || []) walk(c)
    for (const c of node.children || []) walk(c)
  }
  for (const s of sections) walk(s)
}

const prefix = process.argv[2] || ''
const inScope = (num) => !prefix || num === prefix || num.startsWith(prefix + '.')

const wh = new Map()
for (const f of FILES) {
  const mod = await loadModule(path.join(ROOT, 'src', 'data', `${f}.js`))
  const data = mod[Object.keys(mod)[0]]
  flattenWh11ed(data.en, f, wh)
}
// Section 24 Core Abilities lives in reference.js across two exports: `abilityIntro` (the
// framework subsections 24.01/24.02, section-tree shape) and `coreAbilities` (the flat list
// of individual abilities, each already carrying its `num` "24.03" and full text in `fullText`).
// appdata sometimes folds a "Designer's Note" into the SAME container text that wh11ed splits
// into a separate `note` field (e.g. [LETHAL HITS]/[PISTOL]) — include it in the comparison
// body so an already-correct note doesn't read as a content gap. Likewise appdata sometimes
// numbers a clarification as its own child container (e.g. 24.11.01) that wh11ed already
// nests under the parent ability's own `children[]` — walk those too, or they show up as
// permanently "missing" even when transcribed.
const ref = await loadModule(path.join(ROOT, 'src', 'data', 'reference.js'))
flattenWh11ed(ref.abilityIntro.en, 'reference', wh)
for (const a of ref.coreAbilities.en) {
  if (a.num) wh.set(a.num, { title: a.name || '', body: [a.fullText, a.note].filter(Boolean).join('\n\n'), file: 'reference' })
  for (const c of a.children || []) if (c.sectionNum) wh.set(c.sectionNum, { title: c.title || '', body: c.body || '', file: 'reference' })
}

const { rules, dataVersion } = loadJson(path.join(APPDATA, 'factions', '_core-rules.json'))
// appdata numbers a section's intro container "NN.00"; wh11ed carries that intro on the bare
// section node "NN". Collapse "NN.00" → "NN" so the two conventions line up instead of
// reporting every section intro as one missing + one extra.
const canon = (num) => num.replace(/^(\d{2})\.00$/, '$1')
const app = new Map()
for (const r of rules) if (r.num) app.set(canon(r.num), { ...r, num: canon(r.num) })

const appNums = [...app.keys()].filter(inScope).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
const whNums = [...wh.keys()].filter(inScope)

console.log(`sync-core — appdata data_version ${dataVersion}${prefix ? `, section ${prefix}` : ', sections 01-23'}`)
console.log(`  appdata numbered rules in scope: ${appNums.length}, wh11ed: ${whNums.length}\n`)

const lines = []
for (const num of appNums) {
  const a = app.get(num)
  const w = wh.get(num)
  // Two appdata container kinds aren't comparable prose here, so skip them (not wh11ed gaps):
  //  - `stratagem` containers (§15.02+ core stratagems) are already diffed by sync-tracker.mjs
  //    against _core-content.json.coreStratagems, and wh11ed renders them as StratCards, not
  //    numbered subsections.
  //  - `behaviourType` containers (move types: Normal/Advance/Fall-Back/Charge/Pile-In moves…)
  //    carry their rule text in appdata's `behaviour_type` table, which build-factions.mjs does
  //    not yet fold into _core-rules.json — until it does, they have no text to compare (TODO).
  if (a.type === 'stratagem' || !a.text) continue
  if (!w) {
    lines.push(`  + ${num} missing in wh11ed — appdata "${a.title}" (${a.section})`)
    continue
  }
  const ratio = overlap(w.body, a.text)
  if (ratio < 0.55) {
    lines.push(`  ~ ${num} "${w.title}" [${w.file}] low text overlap ${(ratio * 100).toFixed(0)}%  (appdata "${a.title}")`)
  }
}
for (const num of whNums.sort((x, y) => x.localeCompare(y, undefined, { numeric: true }))) {
  if (!app.has(num)) lines.push(`  - ${num} "${wh.get(num).title}" [${wh.get(num).file}] not in appdata (wh11ed-only subsection)`)
}

if (!lines.length) console.log('  no structural gaps; all matched rules above overlap threshold')
else console.log(lines.join('\n'))
console.log(`\n  ${lines.length} finding(s).`)
