// Report-only FULL-TEXT diff between wh11ed's hand-transcribed CORE RULES prose and wh40k-appdata's
// factions/_core-rules.json (generated by that repo's build-factions.mjs from the Core Rules
// publication). This is the one large data pillar that sync-appdata.mjs / sync-tracker.mjs
// never touched — the rulebook text in basicRules/battleRound/advancedRules/battlefields
// (sections 01-23) plus Core Abilities (24) via reference.js. Section 25 (Muster) is included
// too. Section 24's individual abilities and 25 have a different shape than the section-array
// files but are folded in below.
//
// Same architecture as sync-faction-text.mjs / sync-event-companion.mjs: strip wh11ed's
// enrichment layer (gloss tokens, cross-refs, bold) down to bare words on BOTH sides and print
// an actual word-level diff for every matched rule — NOT just a word-overlap ratio. The ratio
// (this script's previous version) was a triage signal only, and has been shown on both faction
// text and Event Companion to both under- and over-report drift (a generic-vocabulary section can
// score high overlap despite being entirely absent; a fully-present but reworded section can score
// low) — see APPDATA-SYNC-LESSONS.md #29. A real diff is strictly more informative and no slower
// to skim, since only genuinely differing text produces output at all.
//
// Usage:
//   node scripts/sync-core.mjs [numPrefix]   # e.g. "03" for just the Moving section
//   node scripts/sync-core.mjs               # all of 01-25
//
// Matching is by rule NUMBER (wh11ed `sectionNum` == appdata container subtitle / numbered
// accordion title, e.g. "03.01.02") — a far more stable key than the rule title, which both
// sides paraphrase. Report only; nothing is written.
import { ROOT, APPDATA, loadJson, loadModule } from './lib/sync-common.mjs'
import path from 'node:path'

// Section-array files (each `{ en: Section[] }` with subsections/children carrying sectionNum):
// basicRules 01-06, battleRound 07-12, battlefields 13-16, advancedRules 17-23, muster 25.
// Section 24 (Core Abilities) is reference.js's flat `coreAbilities` list, wired separately below.
const FILES = ['basicRules', 'battleRound', 'advancedRules', 'battlefields', 'muster']

// appdata's <table>/<b>/<u>/<i> HTML → flat comparable text (tables flattened to cell text, tags
// converted to wh11ed's own conventions where one exists). Same recipe as sync-event-
// companion.mjs's componentText.
function appdataMarkup(text) {
  if (!text) return ''
  return text
    .replace(/<table[^>]*>/gi, '\n')
    .replace(/<\/table>/gi, '\n')
    .replace(/<tr[^>]*>/gi, '\n')
    .replace(/<\/tr>/gi, '')
    .replace(/<\/?t[hd][^>]*>/gi, ' ')
    .replace(/<\/?ul[^>]*>/gi, '\n')
    .replace(/<li[^>]*>/gi, '\n▪ ')
    .replace(/<\/li>/gi, '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<u>(.*?)<\/u>/gis, '__$1__')
    .replace(/<b>(.*?)<\/b>/gis, '**$1**')
    .replace(/<k>(.*?)<\/k>/gis, (_, inner) => inner.toUpperCase())
    .replace(/<i>(.*?)<\/i>/gis, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/&#x?[0-9a-f]+;/gi, ' ') // stray numeric HTML entities (e.g. &#x20;) in appdata text
}

// Strip wh11ed's enrichment layer (and appdata's residual markup, once run through appdataMarkup
// above) down to bare comparable words. Applied to BOTH sides.
function plainText(s) {
  if (!s) return ''
  let t = s
  t = t.replace(/\[img:[^\]]*\]/g, ' ')
  t = t.replace(/\[(?:gloss|def):[^:\]]*:([^\]]*)\]/g, '$1') // [gloss:id:label] / [def:id:label] → label
  t = t.replace(/\{[a-z]+:([^}]*)\}/gi, '$1') // {red:TEXT} → TEXT
  // "Example:" label — sometimes a CSS-generated lead-in on wh11ed's side (.example-block::before,
  // not stored data) with no equivalent stored text, sometimes literal inline text on both sides
  // (e.g. 01.05.01's two inline "**Example:**" paragraphs) — strip on BOTH sides symmetrically so
  // the label token itself is never what a diff hinges on, only the content under it.
  // Same deal for "Designer's Note:" — reference.js's coreAbilities `note` field is rendered via
  // ReferenceView.vue with a CSS-generated "Designer's Note" label (`.note-box::before` there),
  // so appdata's own inline label is redundant, not missing content.
  t = t.replace(/\*\*Example:?\*\*:?\s*/gi, '').replace(/(^|\n)\s*Example:\s*/gi, '$1')
  t = t.replace(/\*\*Designer.s Note:?\*\*:?\s*/gi, '').replace(/(^|\n)\s*Designer.s Note:\s*/gi, '$1')
  t = t.replace(/\*\*/g, '').replace(/__/g, '')
  t = t.replace(/\s*\((?:\d+\.)*\d+(?:\.\d+)*\)/g, '') // (NN) / (NN.NN) cross-refs
  t = t.replace(/[[\]]/g, '') // [KEYWORD] / [ABILITY] bracket markers — both sides have them
  t = t.replace(/[▪•◦▫→◆◈#]/g, ' ')
  t = t.replace(/[’‘`]/g, "'").replace(/[“”«»]/g, '"').replace(/[‐‑–—]/g, '-')
  t = t.replace(/'/g, '')
  t = t.toLowerCase().replace(/[^a-z0-9"/+%-]+/g, ' ').replace(/\s+/g, ' ').trim()
  return t
}
function wordDiff(whPlain, appPlain) {
  const a = whPlain.split(' ')
  const b = appPlain.split(' ')
  let lead = 0
  while (lead < a.length && lead < b.length && a[lead] === b[lead]) lead++
  let tail = 0
  while (tail < a.length - lead && tail < b.length - lead && a[a.length - 1 - tail] === b[b.length - 1 - tail]) tail++
  return { whMid: a.slice(lead, a.length - tail).join(' '), appMid: b.slice(lead, b.length - tail).join(' ') }
}
function compare(out, label, whText, appText) {
  const wh = plainText(whText)
  const app = plainText(appText)
  if (!app && !wh) return
  if (wh === app) return
  if (!wh) {
    out.push(`  + ${label}: wh11ed has no text; appdata:\n      ${appText.replace(/\n/g, '\n      ')}`)
    return
  }
  if (!app) return // nothing on appdata's side to compare against — not our job here
  const { whMid, appMid } = wordDiff(wh, app)
  if (!whMid && !appMid) return
  out.push(`  ~ ${label}: text differs from appdata`)
  if (whMid && appMid) {
    out.push(`      wh11ed:  …${whMid}…`)
    out.push(`      appdata: …${appMid}…`)
  } else if (whMid) {
    out.push(`      wh11ed adds (not in appdata): …${whMid}…`)
  } else {
    out.push(`      appdata has (missing in wh11ed): …${appMid}…`)
  }
  out.push(`      canonical (paste-ready):\n        ${appText.replace(/\n/g, '\n        ')}`)
}

// wh11ed table → flat text (title + headers + rows + footnote), same recipe as sync-event-
// companion.mjs's tableText, so a table edit is caught by the same word diff as prose.
const tableText = (t) => (t ? [t.title, (t.headers || []).join(' '), ...(t.rows || []).map((r) => r.join(' ')), t.footnote].filter(Boolean).join('\n') : '')

// Flatten a wh11ed section-array file's EN tree into num → { title, body, file }.
function flattenWh11ed(sections, file, out) {
  const walk = (node) => {
    const num = node.sectionNum || node.num
    // Section-level nodes keep their intro prose in `description`; subsections use `body`. `note`
    // (Designer's Note / aside), `example` and `table` are genuinely separate wh11ed fields, but
    // appdata inlines all of that into the SAME container text — fold them in here too, or an
    // already-correct note/example/table reads as a content gap purely because of where wh11ed
    // happens to store it.
    if (num) {
      const body = [node.body || node.description, tableText(node.table), node.note, node.example].filter(Boolean).join('\n\n')
      out.set(num, { title: node.title || '', body, file })
    }
    for (const c of node.subsections || []) walk(c)
    for (const c of node.children || []) walk(c)
  }
  for (const s of sections) walk(s)
}

const prefix = process.argv[2] || ''
const inScope = (num) => !prefix || num === prefix || num.startsWith(prefix + '.')

const wh = new Map()
for (const f of FILES) {
  const mod = await loadModule(path.join(ROOT, 'src', 'data', `${f}.js`))
  const data = mod[Object.keys(mod)[0]]
  flattenWh11ed(data.en, f, wh)
  // muster.js's Select Battle Size table is a one-off oddly-placed field: `battleSizeTable` lives
  // on the top-level section-25 node (rendered after 25.03 by MusterView), not as `table` on the
  // 25.03 subsection node itself like every other section-level table in this repo — fold it into
  // 25.03's compared body or it permanently reads as a content gap.
  if (f === 'muster') {
    const bst = data.en[0]?.battleSizeTable
    if (bst && wh.has('25.03')) wh.get('25.03').body += '\n\n' + tableText(bst)
  }
}
// Section 24 Core Abilities lives in reference.js across two exports: `abilityIntro` (the
// framework subsections 24.01/24.02, section-tree shape) and `coreAbilities` (the flat list
// of individual abilities, each already carrying its `num` "24.03" and full text in `fullText`).
// appdata sometimes numbers a clarification as its own child container (e.g. 24.11.01) that
// wh11ed already nests under the parent ability's own `children[]` — walk those too, or they show
// up as permanently "missing" even when transcribed.
const ref = await loadModule(path.join(ROOT, 'src', 'data', 'reference.js'))
flattenWh11ed(ref.abilityIntro.en, 'reference', wh)
for (const a of ref.coreAbilities.en) {
  if (a.num) wh.set(a.num, { title: a.name || '', body: [a.fullText, a.note, a.example].filter(Boolean).join('\n\n'), file: 'reference' })
  for (const c of a.children || []) if (c.sectionNum) wh.set(c.sectionNum, { title: c.title || '', body: c.body || '', file: 'reference' })
}

const { rules, dataVersion } = loadJson(path.join(APPDATA, 'factions', '_core-rules.json'))
// appdata numbers a section's intro container "NN.00"; wh11ed carries that intro on the bare
// section node "NN". Collapse "NN.00" → "NN" so the two conventions line up instead of
// reporting every section intro as one missing + one extra.
const canon = (num) => num.replace(/^(\d{2})\.00$/, '$1')
const app = new Map()
for (const r of rules) if (r.num) app.set(canon(r.num), { ...r, num: canon(r.num) })

const appNums = [...app.keys()].filter(inScope).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
const whNums = [...wh.keys()].filter(inScope)

console.log(`sync-core — appdata data_version ${dataVersion}${prefix ? `, section ${prefix}` : ', sections 01-25'}`)
console.log(`  appdata numbered rules in scope: ${appNums.length}, wh11ed: ${whNums.length}\n`)

const lines = []
for (const num of appNums) {
  const a = app.get(num)
  const w = wh.get(num)
  // Two appdata container kinds aren't comparable prose here, so skip them (not wh11ed gaps):
  //  - `stratagem` containers (§15.02+ core stratagems) are already diffed by sync-tracker.mjs
  //    against _core-content.json.coreStratagems, and wh11ed renders them as StratCards, not
  //    numbered subsections.
  //  - `behaviourType` containers (move types: Normal/Advance/Fall-Back/Charge/Pile-In moves…)
  //    carry their rule text in appdata's `behaviour_type` table, which build-factions.mjs does
  //    not yet fold into _core-rules.json — until it does, they have no text to compare (TODO).
  if (a.type === 'stratagem' || !a.text) continue
  if (!w) {
    lines.push(`  + ${num} missing in wh11ed — appdata "${a.title}" (${a.section}):\n      ${appdataMarkup(a.text).replace(/\n/g, '\n      ')}`)
    continue
  }
  compare(lines, `${num} "${w.title}" [${w.file}] (appdata "${a.title}")`, w.body, appdataMarkup(a.text))
}
for (const num of whNums.sort((x, y) => x.localeCompare(y, undefined, { numeric: true }))) {
  if (!app.has(num)) lines.push(`  - ${num} "${wh.get(num).title}" [${wh.get(num).file}] not in appdata (wh11ed-only subsection)`)
}

if (!lines.length) console.log('  no text differences found')
else console.log(lines.join('\n'))
console.log(`\n  ${lines.length} finding(s).`)
